# Generated by Django 3.0.4 on 2020-03-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255, unique=True, verbose_name='Autor')),
                ('datosautor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Datos Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='CanalTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Cable', 'Cable'), ('Abierto y Cable', 'Abierto y Cable')], max_length=100, null=True, verbose_name='Tipo')),
                ('medio', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Fundación')),
                ('inicioyear', models.IntegerField(blank=True, choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True, verbose_name='Año')),
                ('cobertura', models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Comunal', 'Comunal')], max_length=100, null=True, verbose_name='Cobertura')),
                ('rating', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rating')),
                ('inforating', models.CharField(blank=True, max_length=255, verbose_name='Información de Rating')),
                ('direccion', models.CharField(blank=True, help_text='Calle-Nº-Comuna-Ciudad', max_length=255, verbose_name='Dirección')),
                ('sitioweb', models.URLField(blank=True, help_text='http://...', max_length=255, null=True, verbose_name='Sitio WEB')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anexos', models.TextField(blank=True, null=True, verbose_name='Anexos')),
                ('check', models.BooleanField(default=None, verbose_name='Terminado')),
                ('asociadoacanaltv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canaltv_asociadoacanaltv', to='medioschile.CanalTV', verbose_name='Asociado a Canal de TV')),
            ],
            options={
                'verbose_name': 'Canal de TV',
                'verbose_name_plural': 'Canales de TV',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, unique=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=255, unique=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=255, unique=True, verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutivo', models.CharField(max_length=255, unique=True, verbose_name='Ejecutivo')),
            ],
            options={
                'verbose_name': 'Ejecutivo de Medio',
                'verbose_name_plural': 'Ejecutivos de Medios',
            },
        ),
        migrations.CreateModel(
            name='Empresario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresario', models.CharField(max_length=255, unique=True, verbose_name='Miembro de Directorio')),
            ],
            options={
                'verbose_name': 'Miembro Directorio',
                'verbose_name_plural': 'Miembros de Directorios',
            },
        ),
        migrations.CreateModel(
            name='Escrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Revista', 'Revista')], max_length=100, null=True, verbose_name='Tipo')),
                ('medio', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('pagado_gratuito', models.CharField(blank=True, choices=[('Pagado', 'Pagado'), ('Gratuito', 'Gratuito')], max_length=100, null=True, verbose_name='Pagado o Gratuito')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Fundación')),
                ('inicioyear', models.IntegerField(blank=True, choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True, verbose_name='Año Fundación')),
                ('circulacion', models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Comunal', 'Comunal')], max_length=100, null=True, verbose_name='Circulación')),
                ('lectoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Índice de Lectoría')),
                ('infolectoria', models.CharField(blank=True, max_length=255, verbose_name='Información Lectoría')),
                ('tiraje', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiraje')),
                ('infotiraje', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información Tiraje')),
                ('direccion', models.CharField(blank=True, help_text='Calle-Nº-Comuna-Ciudad', max_length=255, verbose_name='Dirección')),
                ('sitioweb', models.URLField(blank=True, help_text='http://...', max_length=255, null=True, verbose_name='Sitio WEB')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anexos', models.TextField(blank=True, null=True, verbose_name='Anexos')),
                ('check', models.BooleanField(default=None, verbose_name='Terminado')),
                ('asociadoacanaltv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrito_asociadoacanaltv', to='medioschile.CanalTV', verbose_name='Asociado a Canal de TV')),
                ('asociadoaescrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrito_asociadoaescrito', to='medioschile.Escrito', verbose_name='Asociado a Medio Escrito')),
            ],
            options={
                'verbose_name': 'Medio Escrito',
                'verbose_name_plural': 'Medios Escritos',
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=255, unique=True, verbose_name='Fuente')),
                ('descripcionfuente', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('linkfuente', models.URLField(blank=True, help_text='http://...', null=True, verbose_name='Link')),
                ('autor', models.ManyToManyField(blank=True, help_text='Actualice con F5', to='medioschile.Autor', verbose_name='Autor/es')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
            },
        ),
        migrations.CreateModel(
            name='GeneroCanalTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=255, unique=True, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género Canal TV',
                'verbose_name_plural': 'Géneros Canales TV',
            },
        ),
        migrations.CreateModel(
            name='GeneroEscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=255, unique=True, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género Medio Escrito',
                'verbose_name_plural': 'Géneros Medios Escritos',
            },
        ),
        migrations.CreateModel(
            name='GeneroMedioDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=255, unique=True, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género Medio Digital',
                'verbose_name_plural': 'Géneros Medios Digitales',
            },
        ),
        migrations.CreateModel(
            name='GeneroRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=255, unique=True, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género Radio',
                'verbose_name_plural': 'Géneros Radios',
            },
        ),
        migrations.CreateModel(
            name='MedioDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('sitioweb', models.URLField(blank=True, help_text='http://...', max_length=255, null=True, verbose_name='Sitio WEB')),
                ('cobertura', models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Comunal', 'Comunal')], max_length=100, null=True, verbose_name='Cobertura')),
                ('nativoasociado', models.CharField(blank=True, choices=[('Nativo', 'Nativo'), ('Asociado', 'Asociado')], max_length=100, null=True, verbose_name='Nativo o Asociado')),
                ('pagado_gratuito', models.CharField(blank=True, choices=[('Pagado', 'Pagado'), ('Gratuito', 'Gratuito'), ('Gratuito con Contenido Pagado', 'Gratuito con Contenido Pagado')], max_length=100, null=True, verbose_name='Pagado o Gratuito')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Fundación')),
                ('inicioyear', models.IntegerField(blank=True, choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True, verbose_name='Año')),
                ('visitaspaginasvistas', models.IntegerField(blank=True, null=True, verbose_name='Visitas Mes-Páginas Vistas')),
                ('visitasunicas', models.IntegerField(blank=True, null=True, verbose_name='Visitas Mes-Visitas Únicas')),
                ('infovisitas', models.CharField(blank=True, max_length=255, verbose_name='Información de Visitas')),
                ('direccion', models.CharField(blank=True, help_text='Calle-Nº-Comuna-Ciudad', max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anexos', models.TextField(blank=True, null=True, verbose_name='Anexos')),
                ('check', models.BooleanField(default=None, verbose_name='Terminado')),
                ('asociadoacanaltv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediodigital_asociadoacanaltv', to='medioschile.CanalTV', verbose_name='Asociado a Canal de TV')),
                ('asociadoaescrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediodigital_asociadoaescrito', to='medioschile.Escrito', verbose_name='Asociado a Medio Escrito')),
                ('asociadoamediodigital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediodigital_asociadoamediodigital', to='medioschile.MedioDigital', verbose_name='Asociado a Medio Digital')),
            ],
            options={
                'verbose_name': 'Medio Digital',
                'verbose_name_plural': 'Medios Digitales',
            },
        ),
        migrations.CreateModel(
            name='PaisSociedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paissociedad', models.CharField(max_length=255, unique=True, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(max_length=255, unique=True, verbose_name='Periodicidad')),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'verbose_name_plural': 'Periodicidades',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=255, unique=True, verbose_name='Empresa/Sociedad Controladora')),
                ('rutpropietario', models.CharField(blank=True, max_length=255, null=True, verbose_name='R.U.T.')),
                ('utilidades', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utilidades -último año-')),
                ('infoutilidades', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información Utilidades')),
                ('fuentepropietario', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Fuente', verbose_name='Fuente')),
                ('fuenteutilidades', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_utilidades_propietario', to='medioschile.Fuente', verbose_name='Fuente')),
                ('miembrosdirectorio', models.ManyToManyField(blank=True, help_text='Actualice con F5', related_name='propietario_miembrosdirectorio', to='medioschile.Empresario', verbose_name='Miembros Directorio')),
                ('presidentedirectorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propietario_presidentedirectorio', to='medioschile.Empresario', verbose_name='Presidente Directorio')),
            ],
            options={
                'verbose_name': 'Empresa/Sociedad Controladora',
                'verbose_name_plural': 'Empresas/Sociedades Controladoras',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, unique=True, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255, unique=True, verbose_name='Sector de Actividad Socios')),
            ],
            options={
                'verbose_name': 'Sector de Actividad Socio',
                'verbose_name_plural': 'Sectores de Actividad Socios',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodocumento', models.CharField(max_length=255, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Regulación',
                'verbose_name_plural': 'Tipos de Regulación',
            },
        ),
        migrations.CreateModel(
            name='TipoSociedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiposociedad', models.CharField(max_length=255, unique=True, verbose_name='Tipo Sociedad')),
            ],
            options={
                'verbose_name': 'Tipo Sociedad',
                'verbose_name_plural': 'Tipos de Sociedades',
            },
        ),
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociedad', models.CharField(max_length=255, unique=True, verbose_name='Socio')),
                ('rutsociedad', models.CharField(blank=True, max_length=255, null=True, verbose_name='R.U.T.')),
                ('utilidades', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utilidades -último año-')),
                ('infoutilidades', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información Utilidades')),
                ('controlador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlador_socio', to='medioschile.Sociedad', verbose_name='Controlador')),
                ('fuentesociedad', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Fuente', verbose_name='Fuente')),
                ('fuenteutilidades', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_utilidades_sociedad', to='medioschile.Fuente', verbose_name='Fuente')),
                ('miembrosdirectorio', models.ManyToManyField(blank=True, help_text='Actualice con F5', related_name='sociedad_miembrosdirectorio', to='medioschile.Empresario', verbose_name='Miembros Directorio')),
                ('paissocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_socio', to='medioschile.PaisSociedad', verbose_name='País de origen')),
                ('presidentedirectorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sociedad_presidentedirectorio', to='medioschile.Empresario', verbose_name='Presidente Directorio')),
                ('sectores', models.ManyToManyField(blank=True, help_text='Actualice con F5', to='medioschile.Sector', verbose_name='Sectores de Actividad Socio')),
                ('tiposociedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sociedad_tiposociedad', to='medioschile.TipoSociedad', verbose_name='Tipo de Sociedad')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Regulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=255, unique=True, verbose_name='Documento')),
                ('descripciondocumento', models.TextField(blank=True, help_text='Detalle del texto en relación a la industria de medios', null=True, verbose_name='Descripción')),
                ('actores', models.TextField(blank=True, help_text='Nombre de la entidad involucrada(gremio,ong,etc.)-Explicación de la situación(lobby,rrpp,vocería,etc.', null=True, verbose_name='Entidades Involucradas')),
                ('linkdocumento', models.URLField(blank=True, help_text='http://...', null=True, verbose_name='Link')),
                ('tipodocumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.TipoDocumento', verbose_name='Tipo de Regulación')),
            ],
            options={
                'verbose_name': 'Regulación',
                'verbose_name_plural': 'Regulaciones',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('frecuencia', models.CharField(blank=True, choices=[('AM', 'AM'), ('FM', 'FM'), ('AM y FM', 'AM y FM')], max_length=100, null=True, verbose_name='Frecuencia')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Fundación')),
                ('inicioyear', models.IntegerField(blank=True, choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True, verbose_name='Año')),
                ('indiceaudiencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Índice de Audiencia')),
                ('infoaudiencia', models.CharField(blank=True, max_length=255, verbose_name='Información de Índice Audiencia')),
                ('cobertura', models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Comunal', 'Comunal')], max_length=100, null=True, verbose_name='Cobertura')),
                ('direccion', models.CharField(blank=True, help_text='Calle-Nº-Comuna-Ciudad', max_length=255, verbose_name='Dirección')),
                ('sitioweb', models.URLField(blank=True, help_text='http://...', max_length=255, null=True, verbose_name='Sitio WEB')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('anexos', models.TextField(blank=True, null=True, verbose_name='Anexos')),
                ('check', models.BooleanField(default=None, verbose_name='Terminado')),
                ('asociadoacanaltv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radio_asociadoacanaltv', to='medioschile.CanalTV', verbose_name='Asociado a Canal de TV')),
                ('asociadoaescrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radio_asociadoaescrito', to='medioschile.Escrito', verbose_name='Asociado a Medio Escrito')),
                ('asociadoamediodigital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radio_asociadoamediodigital', to='medioschile.MedioDigital', verbose_name='Asociado a Medio Digital')),
                ('asociadoaradio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radio_asociadoaradio', to='medioschile.Radio', verbose_name='Asociado a Radio')),
                ('ciudad', models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si ingresa la(s) comuna(s) correspondientes, no es necesario señalar la(s) ciudad(es).', related_name='radio_ciudad', to='medioschile.Ciudad', verbose_name='Ciudad')),
                ('comuna', models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si el medio tiene cobertura regional, no es necesario ingresar las comunas.', to='medioschile.Comuna', verbose_name='Comuna')),
                ('fuenteaudiencia', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_audiencia_radio', to='medioschile.Fuente', verbose_name='Fuente Audiencia')),
                ('fuentepropiedad', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_propiedad_radio', to='medioschile.Fuente', verbose_name='Fuente Propiedad')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radio_genero', to='medioschile.GeneroRadio')),
                ('propietario', models.ManyToManyField(blank=True, help_text='Actualice con F5', max_length=255, related_name='propietario_radio', to='medioschile.Propietario', verbose_name='Empresa Controladora')),
                ('region', models.ManyToManyField(blank=True, related_name='radio_region', to='medioschile.Region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
            },
        ),
        migrations.AddField(
            model_name='propietario',
            name='sectores',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5', to='medioschile.Sector', verbose_name='Sectores de Actividad Socio'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='tiposociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propietario_tiposociedad', to='medioschile.TipoSociedad', verbose_name='Tipo de Sociedad'),
        ),
        migrations.CreateModel(
            name='PorcentajePropietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajesocio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Porcentaje')),
                ('fechaporcentaje', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fuenteporcentajesocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Fuente', verbose_name='Fuente')),
                ('propietarioporcentaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Propietario')),
                ('socioporcentaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socio_porcentajep', to='medioschile.Sociedad', verbose_name='Socio')),
            ],
            options={
                'verbose_name_plural': 'Porcentajes Socios',
            },
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='asociadoaradio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediodigital_asociadoaradio', to='medioschile.Radio', verbose_name='Asociado a Radio'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='ciudad',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si ingresa la(s) comuna(s) correspondientes, no es necesario señalar la(s) ciudad(es).', related_name='mediodigital_ciudad', to='medioschile.Ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='comuna',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si el medio tiene cobertura regional, no es necesario ingresar las comunas.', to='medioschile.Comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='fuentepropiedad',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_propiedad_mediodigital', to='medioschile.Fuente', verbose_name='Fuente Propiedad'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='fuentevisitas',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_visitas_mediodigital', to='medioschile.Fuente', verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediodigital_genero', to='medioschile.GeneroMedioDigital'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='propietario',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5', max_length=255, related_name='propietario_mediodigital', to='medioschile.Propietario', verbose_name='Empresa Controladora'),
        ),
        migrations.AddField(
            model_name='mediodigital',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='mediodigital_region', to='medioschile.Region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='asociadoamediodigital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrito_asociadoamediodigital', to='medioschile.MedioDigital', verbose_name='Asociado a Medio Digital'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='asociadoaradio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrito_asociadoaradio', to='medioschile.Radio', verbose_name='Asociado a Radio'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='ciudad',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si ingresa la(s) comuna(s) correspondientes, no es necesario señalar la(s) ciudad(es).', to='medioschile.Ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='comuna',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si el medio tiene cobertura regional, no es necesario ingresar las comunas.', to='medioschile.Comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='fuentelectoria',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_lectoria_escrito', to='medioschile.Fuente', verbose_name='Fuente Lectoría'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='fuentepropiedad',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_propiedad_escrito', to='medioschile.Fuente', verbose_name='Fuente Propiedad'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='fuentetiraje',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_tiraje_escrito', to='medioschile.Fuente', verbose_name='Fuente Tiraje'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.GeneroEscrito'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='periodicidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Periodicidad', verbose_name='Periodicidad'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='propietario',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5', max_length=255, related_name='propietario_escrito', to='medioschile.Propietario', verbose_name='Empresa Controladora'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='region',
            field=models.ManyToManyField(blank=True, to='medioschile.Region', verbose_name='Región'),
        ),
        migrations.CreateModel(
            name='CargoEjecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacargo', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('canaltv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.CanalTV')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_ejecutivo', to='medioschile.Cargo', verbose_name='Cargo')),
                ('ejecutivocargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecutivo_cargo', to='medioschile.Ejecutivo', verbose_name='Ejecutivo')),
                ('escrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Escrito')),
                ('mediodigital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.MedioDigital')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medioschile.Radio')),
            ],
            options={
                'verbose_name': 'Cargo Ejectutivo',
                'verbose_name_plural': 'Cargos Ejecutivos',
            },
        ),
        migrations.AddField(
            model_name='canaltv',
            name='asociadoaescrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canaltv_asociadoaescrito', to='medioschile.Escrito', verbose_name='Asociado a Medio Escrito'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='asociadoamediodigital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canaltv_asociadoamediodigital', to='medioschile.MedioDigital', verbose_name='Asociado a Medio Digital'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='asociadoaradio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canaltv_asociadoaradio', to='medioschile.Radio', verbose_name='Asociado a Radio'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='ciudad',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si ingresa la(s) comuna(s) correspondientes, no es necesario señalar la(s) ciudad(es).', related_name='canaltv_ciudad', to='medioschile.Ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='comuna',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5 - Si el medio tiene cobertura regional, no es necesario ingresar las comunas.', to='medioschile.Comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='fuentepropiedad',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_propiedad_canaltv', to='medioschile.Fuente', verbose_name='Fuente Propiedad'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='fuenterating',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_rating_canaltv', to='medioschile.Fuente', verbose_name='Fuente Rating'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canaltv_genero', to='medioschile.GeneroCanalTV'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='propietario',
            field=models.ManyToManyField(blank=True, help_text='Actualice con F5', max_length=255, related_name='propietario_canaltv', to='medioschile.Propietario', verbose_name='Empresa Controladora'),
        ),
        migrations.AddField(
            model_name='canaltv',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='canaltv_region', to='medioschile.Region', verbose_name='Región'),
        ),
    ]
